
services:
  server:
    build:
      context: .
    container_name: node-compose
    command: sh -c "npm install -g nodemon && npm install && npm run dev"
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app/src

